apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: new-container
        image: ashrafatef3232/node-app:latest
        ports:
        - containerPort: 3000
        # Add liveness probe
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
